name: Deploy

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_STRAPI_DEPLOY}}
          heroku_app_name: "Strapi_backend" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
          branch: "dev"
